### ISSUE TITLE
Get Pre-signed url working (from Frontend)

### ISSUE THREAD

**Issue by thanawinboon** [thanawat-toktik/toktik-frontend#10]
- From frontend, integrate s3-related libraries that allows for getting Pre-signed url
- Make that functional with the UI

**Comment by nngerncham** [comment]
**To-dos**:
- [x] Implement the front end (UI)
- [x] Connect front end to S3 and be able to upload from raw URL
- [x] Connect front end to S3 and be able to fetch the presigned URL
- [x] Test for uploading
